@address=localhost:9000


### create order
POST http://{{address}}/order
Content-Type: application/json

{
	"exchange": "binance",
    "marketId": "LTCUSDT",
	"side": "buy",
	"quantity": 0.2,
	"price": 125
}
