@address=localhost:9000


### create order
POST http://{{address}}/order
Content-Type: application/json

{
	"exchange": "binance",
    "marketId": "LTCUSDT",
	"side": "buy",
	"quantity": 0.15,
	"price": 125
}

### query order
GET  http://{{address}}/order
Content-Type: application/json

{
	"id": 2750377045,
    "marketId": "LTCUSDT"
}

### cancel order
DELETE   http://{{address}}/order
Content-Type: application/json

{
	"id": 2750377045,
    "marketId": "LTCUSDT"
}
